### ISSUE TITLE
Remainder checklist

### ISSUE THREAD

**Issue by TalDerei** [td-kwj-zp2023/webgpu-msm-twisted-edwards#74]
**Housekeeping:**
- [x] Enable public read access to the codebase on March 14th
- [x] Enable public read access to the benchmarks spreadsheet on March 14th
- [x] Enable public read access to documentation on March 14th
- [x] Comprehensive documentation in Readme https://hackmd.io/HNH0DcSqSka4hAaIfJNHEA
- [x] #135
- [x] Review WASM codebase (https://github.com/mitschabaude/montgomery) for optimization ideas
- [x] Investigate load imbalance for nonuniform inputs compared with uniformly distributed inputs. 
- [x] Optimize storage buffer usage by profiling memory usage 
- [x] Investigate scalar chunk sizes greater than 16 https://github.com/TalDerei/webgpu-msm/issues/47
- [x] Lower level shader optimizations (eg. Refactor to pass constants like p as pointers)
- [x] #104 
- [x] Create a diagram that visually explains the end-to-end flow https://app.diagrams.net/#G1gKe37GI3oT-H-gZyKa7s4yOo2QVI-kuK
- [x] Testing in production build #10 
- [x] Fix naming: is SMVP actually bucket accumulation and is the tree-summation step actually bucket summation or reduction? The docs and the code should use the same terminology.
- [x] Implement SMVP shader logic in end-to-end flow
- [x] Implement multiply operation after SMVP (before Horner's Rule reduction)
- [x] Handle OOMs for `2^19 / 2^20` inputs by refactoring / splitting up buffer layout 
- [x] Determine the optimal chunk size as a function of the input-size at runtime
- [x] Remove unused code (WASM and Web-Worker) in main branch of submission #93 
- [x]  Extraneous templating engine considerations + naga hack
- [x] Shader organization
- [x] Return single point (320 bytes) from aggregate_buckets
- [x] Implement and benchmark running sum vs tree summation method
- [x] Optimisation: combine `convert_point_coords.template.wgsl` and `decompose_scalars.template.wgsl`
- [x] Implement signed bucket indices for cuZK (https://hackmd.io/EKApBmBGS6iG-V3y11dREw)
- [x] Optimization: Perform pre-computation for all subtasks in a single shader (a big task)
- [x] Ensure that input sizes like 2 ** 16 + 1 work (no need - fulltimemike said inputs will be powers of 2)
- [x] A one-click benchmarking suite for all input sizes and variables such as chunk sizes, workgroup sizes, etc
- [x] Investigate exceeding the workgroup size limits does not cause a failure. 
- [x] Create submission branch https://github.com/TalDerei/webgpu-msm/pull/110
